const LOGIN_ERROR = "LOGIN ERROR";
const INTERNAL_ERROR = "INTERNAL ERROR";
const BAD_REQUEST = "BAD REQUEST";
const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
const NOT_FOUND = "NOT_FOUND";

module.exports = {
  LOGIN_ERROR,
  INTERNAL_ERROR,
  BAD_REQUEST,
  NOT_FOUND,
  AUTHENTICATION_ERROR,
};
