[[headers]]
    for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"